### PR TITLE
enzyme shallow

### PR DESCRIPTION
**Pull request by ghost**
Sry, I am so BAD at using github, due to double pr change at the same file. The merge conflict, cannot be fix by me (I don't know). The best solution, make a new one.

10+ methods of shallow.

### CODE REVIEW

**Comment by ayushyamitabh** [comment]
@LiuYuHao This is meant to be a template for us so that we can write the rest of the enzyme tests right?

**Comment by LiuYuHao** [comment]
@ayushyamitabh Yes, there are more methods on the website. There are 10+ examples, the main thing is to know about the format

**Review by ayushyamitabh — APPROVED** [review]
Well done @LiuYuHao ! Thank you for the helpful comments.

**Review by edwin0108 — APPROVED** [review]
Great job! Thank you for the sample code and I think this can be merge to master

**Pull request merged**
