### PR TITLE
Resolve all syntax errors

### PR DESCRIPTION
**Pull request by khelif96**
Resolve all syntax errors it should allow the  deploy build to pass

### CODE REVIEW

**Comment by whuang001** [comment]
approved

**Comment by ayushyamitabh** [comment]
Should delayed.jsx be removed? I dont think it's being used

**Comment by khelif96** [comment]
> approved
@whuang001  you can use github to issue the approval click on files changed then review changes then approve

**Comment by khelif96** [comment]
> Should delayed.jsx be removed? I dont think it's being used

Just removed it

**Pull request merged**
